openapi: 3.0.0
info:
  title: Support Agent API
  version: 1.0.0

paths:
  /ask:
    post:
      summary: Задать вопрос агенту
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
      responses:
        "200":
          description: Ответ агента
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string

  /history:
    get:
      summary: Получить историю чата
      responses:
        "200":
          description: История сообщений
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    role:
                      type: string
                    content:
                      type: string

    delete:
      summary: Очистить историю чата
      responses:
        "200":
          description: История очищена
