FROM node:20-alpine

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем весь проект
COPY . .

# Открываем порт (если сервер слушает 3000, поменяй при необходимости)
EXPOSE 3000

# Запуск приложения
CMD ["node", "server.js"]
